version: "3"

services:
  app:
    build: 
      context: .
      dockerfile: ./docker/m1/Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - .env
    volumes:
      - ./models:/usr/src/app/models