name: Docker

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ai-box-controller

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: github.event_name == 'push'
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: >-
          docker buildx build --push 
          --file ./Dockerfile 
          --tag ghcr.io/premai-io/$IMAGE_NAME:latest 
          --platform linux/arm64,linux/amd64 .
