name: "Publish prem mock images"

on:
  push:
    branches: ["main"]

jobs:
  push-mocks:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push prem
        run:  >-
          docker buildx build --push
          --file ./resources/mocks/generic/Dockerfile
          --tag ghcr.io/premai-io/chat-mock-small:latest
          --tag ghcr.io/premai-io/chat-mock-medium:latest
          --tag ghcr.io/premai-io/chat-mock-large:latest
          --platform linux/arm64,linux/amd64 ./resources/mocks/generic
