name: CI

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_CLI_EXPERIMENTAL: "enabled"

on:
  pull_request:
    branches: ["main"]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Create the .env file from example
        run: cp .env.example .env

      - name: Build the Stack
        run: docker-compose build

      - name: Run APIs Tests
        run: docker-compose run premd pytest

      - name: Tear down the Stack
        run: docker-compose down
