name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push SHA Images
        run: |
          docker system prune -f -a
          docker pull filippopedrazzini/the_ai_box:latest || true
          docker build -t filippopedrazzini/the_ai_box:$GITHUB_SHA -t filippopedrazzini/the_ai_box:latest .
          docker push filippopedrazzini/the_ai_box:$GITHUB_SHA
          docker push filippopedrazzini/the_ai_box:latest
